name: Deploy Laravel App

on:
  push:
    branches:
      - master  # Trigger deployment on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io  # The GHCR registry
          username: ${{ github.actor }}  # Use the GitHub username of the current user
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
#          password: ${{ github.token }}  # GitHub token for authentication

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner | toLowerCase() }}/laravel-app:latest  # Tag format for GHCR

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # SSH to the server and deploy using CapRover
      - name: Deploy to CapRover
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }} # or use private key authentication
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest
            caprover deploy --appName my-laravel-app --imageName ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest
